version: '3'
services:
  nodejs-server:
    image: node
    ports:
      - "3080:3080"
    container_name: node-api
#  vue-ui:
#    build:
#      context: ./docker/node/
#    ports:
#      - "8080:8080"
#    container_name: vue-ui